// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package gov.dhs.uscis.efile.domain;

import gov.dhs.uscis.efile.domain.Applicant;
import gov.dhs.uscis.efile.domain.ApplicantDataOnDemand;
import gov.dhs.uscis.efile.domain.ApplicantIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ApplicantIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ApplicantIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ApplicantIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ApplicantIntegrationTest: @Transactional;
    
    @Autowired
    private ApplicantDataOnDemand ApplicantIntegrationTest.dod;
    
    @Test
    public void ApplicantIntegrationTest.testCountApplicants() {
        Assert.assertNotNull("Data on demand for 'Applicant' failed to initialize correctly", dod.getRandomApplicant());
        long count = Applicant.countApplicants();
        Assert.assertTrue("Counter for 'Applicant' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ApplicantIntegrationTest.testFindApplicant() {
        Applicant obj = dod.getRandomApplicant();
        Assert.assertNotNull("Data on demand for 'Applicant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Applicant' failed to provide an identifier", id);
        obj = Applicant.findApplicant(id);
        Assert.assertNotNull("Find method for 'Applicant' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Applicant' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ApplicantIntegrationTest.testFindAllApplicants() {
        Assert.assertNotNull("Data on demand for 'Applicant' failed to initialize correctly", dod.getRandomApplicant());
        long count = Applicant.countApplicants();
        Assert.assertTrue("Too expensive to perform a find all test for 'Applicant', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Applicant> result = Applicant.findAllApplicants();
        Assert.assertNotNull("Find all method for 'Applicant' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Applicant' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ApplicantIntegrationTest.testFindApplicantEntries() {
        Assert.assertNotNull("Data on demand for 'Applicant' failed to initialize correctly", dod.getRandomApplicant());
        long count = Applicant.countApplicants();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Applicant> result = Applicant.findApplicantEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Applicant' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Applicant' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ApplicantIntegrationTest.testFlush() {
        Applicant obj = dod.getRandomApplicant();
        Assert.assertNotNull("Data on demand for 'Applicant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Applicant' failed to provide an identifier", id);
        obj = Applicant.findApplicant(id);
        Assert.assertNotNull("Find method for 'Applicant' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyApplicant(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Applicant' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicantIntegrationTest.testMergeUpdate() {
        Applicant obj = dod.getRandomApplicant();
        Assert.assertNotNull("Data on demand for 'Applicant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Applicant' failed to provide an identifier", id);
        obj = Applicant.findApplicant(id);
        boolean modified =  dod.modifyApplicant(obj);
        Integer currentVersion = obj.getVersion();
        Applicant merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Applicant' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicantIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Applicant' failed to initialize correctly", dod.getRandomApplicant());
        Applicant obj = dod.getNewTransientApplicant(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Applicant' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Applicant' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Applicant' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ApplicantIntegrationTest.testRemove() {
        Applicant obj = dod.getRandomApplicant();
        Assert.assertNotNull("Data on demand for 'Applicant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Applicant' failed to provide an identifier", id);
        obj = Applicant.findApplicant(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Applicant' with identifier '" + id + "'", Applicant.findApplicant(id));
    }
    
}
