// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package gov.dhs.uscis.efile.domain;

import gov.dhs.uscis.efile.domain.Evidence;
import gov.dhs.uscis.efile.domain.EvidenceDataOnDemand;
import gov.dhs.uscis.efile.domain.EvidenceIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EvidenceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EvidenceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EvidenceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EvidenceIntegrationTest: @Transactional;
    
    @Autowired
    private EvidenceDataOnDemand EvidenceIntegrationTest.dod;
    
    @Test
    public void EvidenceIntegrationTest.testCountEvidences() {
        Assert.assertNotNull("Data on demand for 'Evidence' failed to initialize correctly", dod.getRandomEvidence());
        long count = Evidence.countEvidences();
        Assert.assertTrue("Counter for 'Evidence' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EvidenceIntegrationTest.testFindEvidence() {
        Evidence obj = dod.getRandomEvidence();
        Assert.assertNotNull("Data on demand for 'Evidence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Evidence' failed to provide an identifier", id);
        obj = Evidence.findEvidence(id);
        Assert.assertNotNull("Find method for 'Evidence' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Evidence' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EvidenceIntegrationTest.testFindAllEvidences() {
        Assert.assertNotNull("Data on demand for 'Evidence' failed to initialize correctly", dod.getRandomEvidence());
        long count = Evidence.countEvidences();
        Assert.assertTrue("Too expensive to perform a find all test for 'Evidence', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Evidence> result = Evidence.findAllEvidences();
        Assert.assertNotNull("Find all method for 'Evidence' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Evidence' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EvidenceIntegrationTest.testFindEvidenceEntries() {
        Assert.assertNotNull("Data on demand for 'Evidence' failed to initialize correctly", dod.getRandomEvidence());
        long count = Evidence.countEvidences();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Evidence> result = Evidence.findEvidenceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Evidence' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Evidence' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EvidenceIntegrationTest.testFlush() {
        Evidence obj = dod.getRandomEvidence();
        Assert.assertNotNull("Data on demand for 'Evidence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Evidence' failed to provide an identifier", id);
        obj = Evidence.findEvidence(id);
        Assert.assertNotNull("Find method for 'Evidence' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEvidence(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Evidence' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EvidenceIntegrationTest.testMergeUpdate() {
        Evidence obj = dod.getRandomEvidence();
        Assert.assertNotNull("Data on demand for 'Evidence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Evidence' failed to provide an identifier", id);
        obj = Evidence.findEvidence(id);
        boolean modified =  dod.modifyEvidence(obj);
        Integer currentVersion = obj.getVersion();
        Evidence merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Evidence' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EvidenceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Evidence' failed to initialize correctly", dod.getRandomEvidence());
        Evidence obj = dod.getNewTransientEvidence(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Evidence' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Evidence' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Evidence' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EvidenceIntegrationTest.testRemove() {
        Evidence obj = dod.getRandomEvidence();
        Assert.assertNotNull("Data on demand for 'Evidence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Evidence' failed to provide an identifier", id);
        obj = Evidence.findEvidence(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Evidence' with identifier '" + id + "'", Evidence.findEvidence(id));
    }
    
}
