// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package gov.dhs.uscis.efile.domain;

import gov.dhs.uscis.efile.domain.Applicant;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Applicant_Roo_Configurable {
    
    declare @type: Applicant: @Configurable;
    
}
